export const MessageConstant = {
  INTERNAL_SERVER_ERROR: 'Oops! Something went wrong',
  NOT_FOUND: 'Resource not found',
  UNAUTHORIZED: 'Unauthorized',
  FORBIDDEN: 'Forbidden',
  BAD_REQUEST: 'Bad Request',
  TOKEN_INVALID: 'Token is invalid',
  TOKEN_EXPIRED: 'Token is expired',
  EMAIL_NOT_VERIFIED: 'Email is not verified',
  SESSION_EXPIRED: 'Session expired',
  FILE_SIZE_TOO_LARGE: 'File size is too large (max 10MB)',
  FILE_TYPE_NOT_SUPPORTED: 'File type is not supported',
  EMAIL_OR_PASSWORD_INCORRECT: 'Email or password is incorrect',
  REGISTER_SUCCESS: 'Register successfully',
  REGISTER_FAILED: 'Register failed',
  LOGIN_SUCCESS: 'Login successfully',
  LOGIN_FAILED: 'Login failed',
  LOGOUT_SUCCESS: 'Logout successfully',
  EMAIL_VERIFIED: 'Email is verified',
  EMAIL_ALREADY_EXISTS: 'Email already exists',
};
