export abstract class StatusConstants {
  static SUCCESS = 'SUCCESS';
  static ERROR = 'ERROR';
  static NOT_FOUND = 'NOT_FOUND';
  static UNAUTHORIZED = 'UNAUTHORIZED';
  static FORBIDDEN = 'FORBIDDEN';
  static BAD_REQUEST = 'BAD_REQUEST';
  static INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
  static NOT_IMPLEMENTED = 'NOT_IMPLEMENTED';
  static SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE';
  static GATEWAY_TIMEOUT = 'GATEWAY_TIMEOUT';
  static TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS';
  static REQUEST_TIMEOUT = 'REQUEST_TIMEOUT';
}
